// Advanced C++.h : Include file for standard system include files,
// or project specific include files.
#ifndef MAIN_H
#define MAIN_H
#include "accontrol.h"
#include "aggeregate.h"
#include "associative.h"
#include "bind.h"
#include "container.h"
#include "ctor.h"
#include "fileinout.h"
#include "friendbs.h"
#include "function.hpp"
#include "funobj.h"
#include "generic.h"
#include "iochap.h"
#include "iolib.h"
#include "iterators.h"
#include "libfac.h"
#include "m_sales.h"
#include "max_sub.hpp"
#include "msgcl.h"
#include "objector.h"
#include "operator.hpp"
#include "overload.h"
#include "problem.h"
#include "query.h"
#include "rassoc.h"
#include "rgeneric.h"
#include "rsales.h"
#include "rval.h"
#include "sales.h"
#include "screen.h"
#include "seqcontainer.h"
#include "smartpo.h"
#include "statement.hpp"
#include "stroper.h"
#include "strvec.h"
#include "templ.h"
#include <iostream>
#endif
// TODO: Reference additional headers your program requires here.
